### PR TITLE
Update elementTransitions.js

### PR DESCRIPTION
**Pull request by DJChloe**
The "et-rotate" element can be a sub-sub-...-sub-child  of the et-page element with this little modification (lines 65-69).
+Some typos lines 13, 48 and 59 (missing semicolons)
It permits some complex layout, like a "multi-page" form
Example (multipage form, with transitions ) :
```
<form action="xxx/yyy.php" method="post">
<div class="et-page">
	<h2>What is your choice ? </h2>
    <ul>
              //page transition occurs on item click
		<li class="et-rotate" et-in="rotateCarouselLeftIn" et-out="rotateCarouselLeftOut"><input type="radio" value="1">Choice 1</label></li>
		<li class="et-rotate" et-in="rotateCarouselLeftIn" et-out="rotateCarouselLeftOut"><input type="radio" value="2">Choice 2</label></li>
                <li class="et-rotate" et-in="rotateCarouselLeftIn" et-out="rotateCarouselLeftOut"><input type="radio" value="3">Choice 3</label></li>

	</ul>
</div>
<div class="et-page">
	<p> What is your First name ?	</p>	
        <label for="fNAME">First Name </label>
	<input type="text" value="Write your first name here" name="fNAME" class="" id="fNAME">				
	<div class="ca-btncontainer">
		//this is a div button , it is centered in ca-btncontainer
		<div class="ca-btn ca-btn-warning et-rotate" et-in="rotateCarouselLeftIn" et-out="rotateCarouselLeftOut">Clik here !</div>
	</div>
</div>
<div class="et-page">
	<p> And your Last name ?	</p>	
        <label for="lNAME">Last Name </label>
	<input type="text" value="Write your last name here" name="lNAME" class="" id="lNAME">				
	<input type="submit" value="OK, I validate" class="button">
</div>
</form>
```

### CODE REVIEW

**Comment by DJChloe** [comment]
for javascript validation (for instance typos), I use this online tool : http://jshint.com/

**Comment by dan-silver** [comment]
Thanks for the pull request!  You're absolutely right that the current implementation is very limited and the et-rotate element must be directly below or at the same level as et-wrapper.

**Comment by dan-silver** [comment]
Merged in 08a28c8df3a289623f76b1a2b7dc9f1aca579d85 and 7558ed109f820902b0f39d63650ca12f4c21dd79

Thanks!

**Comment by DJChloe** [comment]
Happy to help and improve :)

Now you will have to add à 4th example on the web page to explain that :)

Best regards,
Chloé Avrillon

**Comment by DJChloe** [comment]
I have to precise that for a full page layout, ones need to override the et-wrapper css

.et-wrapper {
	position: absolute;
	width: 100%;
	height: 100%;
	top: 0;
	left: 0;
}

**Pull request merged**
